codecov_cli/helpers/request.py
codecov_cli/services/upload/upload_collector.py
codecov_cli/services/upload/upload_sender.py
tests/services/commit/test_commit_service.py
tests/services/report/test_report_results.py
tests/services/report/test_report_service.py
tests/services/upload/test_upload_service.py

Trying to strike the right balance between verbose and non-verbose mode in the CLI.
Particularly for the upload command it's been not satisfactory. The list of files being uploaded as coverage is now listed in non-verbose mode.
Plus there's a positive feedback now that the process (command) finished - for ALL commands. So you know that at least the CLI did its thing, even though there might still be errors.
And again for the upload command, separate better the response from codecov-api and the response from the PUT request afterwards.
To help debugging and all that.

Improve logging

---

codecov_cli/commands/labelanalysis.py
codecov_cli/runners/dan_runner.py
codecov_cli/runners/python_standard_runner.py
codecov_cli/runners/types.py
tests/runners/test_dan_runner.py
tests/runners/test_python_standard_runner.py
tests/runners/test_runners.py
tests/runners/test_types.py

TypedDict became part of typing in Python 3.8
We are interested in supporting the CLI in earlier versions of Python 3, so removing it.
It's a bit hacky, but works.
I was careful to make sure we are casting to the new types so we can use the properties if we choose to do so.

Removed TypedDict

---

codecov_cli/services/empty_upload/__init__.py
tests/services/empty_upload/test_empty_upload.py

After merging the empty upload PR into master, the logging tests failed due to a change made earlier 
This PR fixes the failing tests and remove the logging of the result as we already do that along with the errors and warnings

fix failing tests

---

codecov_cli/plugins/__init__.py
codecov_cli/plugins/pycoverage.py
tests/plugins/test_instantiation.py
tests/plugins/test_pycoverage.py

These changes improve the existing Pycoverage plugin.
This plugin runs `coverage` util (from pytest-cov) to generate human-readable reports from .coverage files.
Up to this point it would generate XML files. But it can also generate JSON files.
This is relevant because ATS uses the JSON format. So far we've been telling users to add another step
to their CI to create the files directly calling `coverage`, but the plugin can handle it for us.
In these changes we include config options that allow us to decide what report file to generate,
plus other things like giving the path directly, and options specific to the JSON reports.

Add config options to pycoverage plugin

---

.github/workflows/push_flow.yml
codecov_cli/plugins/__init__.py
codecov_cli/plugins/compress_pycoverage_contexts.py
requirements.in
requirements.txt
setup.py
tests/plugins/test_compress_pycoverage_contexts.py
tests/plugins/test_instantiation.py

Recently we've noticed that JSON reports with labels - the one format accepted by ATS -
are simply too big. It is likely that we are experiencing Out Of Memory errors when
trying to process them.
To put it in perspective, below is a comparison between reports with no labels and
with labels for the worker repo full test suite.
```
918951 bytes (897Kb) May 15 19:45 coverage.xml # this is the regular coverage with no labels
26607438 bytes (25Mb)  May 15 19:48 label.coverage.json # this is all labels, stock
```
To avoid processing issues and save bandwidth and all that we will be compressing these reports.
The compression idea is simple: we build a mapping label --> int that will substitute the label itself
in the report (usually large-ish strings) for a number in the "contexts" of each file. …

Create plugin to compress ATS reports

---

codecov_cli/commands/labelanalysis.py
codecov_cli/runners/dan_runner.py
tests/commands/test_invoke_labelanalysis.py
tests/runners/test_dan_runner.py

We had created a DAN runner previously, but there was no option in the label analysis
command to actually select different runners.
Another issue is that thwe return of `collect_tests` in a runner needs to be a list,
and the DAN runner was not returning that.
The changes here should make the DAN runner a viable alternative to the
PythonStandardRunner, in case we need that.

Enable other runners (DAN runner)

---

codecov_cli/services/staticanalysis/analyzers/general.py
codecov_cli/services/staticanalysis/analyzers/javascript_es6/__init__.py
codecov_cli/services/staticanalysis/analyzers/python/__init__.py
samples/example_module.js
samples/inputs/sample_003.js
samples/outputs/sample_003.json

This PR:
- moves getting the import lines to the base Analyzer
- adds a import_query_str for js that we use to search for import lines
- analyzer returns the import lines 
Note that JS has static and dynamic imports.[ Static imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) use import, when [dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) use import() 
imports_query_str = """
(import_statement) @elemen ====> this is for static imports
(import) @elemen =====> this is for dynamic imports 
"""
Ticket: [CODE-3136](https://codecovio.atlassian.net/browse/CODE-3136?atlOrigin=eyJpIjoiOTIyNDFmMTdhOWY0NGE1Y2JmMWYxZDZlNzkxNTdjMDYiLCJwIjoiaiJ9)
[CODE-3136]: …

search for imports, add them to the JS analyzer

---

codecov_cli/commands/labelanalysis.py
tests/commands/test_invoke_labelanalysis.py

This option allows customers to decide how long they want to way for the label analysis result
(e.g. the set of labels to run) before falling back to running the entire test suite.
I'm adding this option because on one occasion I've seen it taking more than 40min to get a response.
No doubt some processing error happened and it failed silently, or something like that, and the user's
CI just waited until it too was killed (for taking too long).
One brute force solution is to just have a configurable time limit.
Also taking this opportunity to refactor a little bit label analysis and improve coverage.

Add --max-wait-time option for label analysis

---

codecov_cli/runners/__init__.py
tests/runners/test_runners.py

The trickiest part of ATS is the runner system.
Every customer will have their own test process, and we can't hope to
accomodate all of them. While we will try to provider the most used
runners for them, giving them the option to decide what runner they'll use
is a good idea.
These changes enable the dynamic import of runners.
It works by defining the runner in the yaml config.

Enable custom runners

---

codecov_cli/helpers/request.py
tests/data/reports_examples.py
tests/helpers/test_upload_sender.py

When running locally, we get a response back from server that `Content-Length` is not set. This is seen to be true, that `requests` does not automatically add a `Content-Length` header. 
However, sending the `post` data as `json` seems to solve this case.

fix: send post data as json

---

codecov_cli/services/staticanalysis/analyzers/general.py
codecov_cli/services/staticanalysis/analyzers/javascript_es6/__init__.py
samples/inputs/sample_004.js
samples/outputs/sample_003.json
samples/outputs/sample_004.json
tests/services/static_analysis/test_analyse_file.py

JS has different types of functions
1- Function Declarations: These are defined with the function keyword. They are identified by `function_declaration`
example:
```
function add(a, b) {
return a + b;
}
```
2- Function expressions: These are functions that are assigned to variables or other data structures. They are identified by `function`
example: 
`var b = function() {};`
3- Arrow Functions: These are a shorthand syntax for writing functions in JavaScript. They are identified by `arrow_function` 
example:
`async (a) => { return foo; };`
4-Generator Functions: These are special functions that can be paused and resumed. They are defined using the `function* `syntax and use the yield keyword. Identified by `generator_function_declaration`
example:
`async function* foo() { yield 1; }`
5- …

add all types of JS functions to function_query_str

---

codecov_cli/runners/python_standard_runner.py
tests/runners/test_python_standard_runner.py

Previously (around commit 8c5b289c90a6be8f53eb13babb2a19ef24e1b6ab) we had removed `subprocess.run` from the `PythonStandardRunner` to make it extra safe. Instead the default way of using it was calling `pytest` directly from Python.
The thing is that Python import process when running pytest from Python can get messy. Because imported modules are cached. Out of the blue we started seeing "pytest.PytestAssertRewriteWarning" errors. The most likely cause is that some modules are imported by the CLI, and when the process that runs Pytest is created it inherits some of the parent's process resources ([because it's forked](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods)). Yes I tried with "spawn" instead of "fork" but that didn't work either /:
However …

Patch import errors (the return of subprocess.run)

---

codecov_cli/services/staticanalysis/analyzers/general.py
codecov_cli/services/staticanalysis/analyzers/javascript_es6/__init__.py
codecov_cli/services/staticanalysis/analyzers/javascript_es6/node_wrappers.py
codecov_cli/services/staticanalysis/analyzers/python/__init__.py
samples/inputs/sample_003.js
samples/inputs/sample_004.js
samples/outputs/sample_003.json
samples/outputs/sample_004.json

these changes add statement lines to the JS static analyzer. I added more tests that include if statements, for loops and do_while all with and without {} "curly braces" 
ticket: [CODE-3136](https://codecovio.atlassian.net/browse/CODE-3136?atlOrigin=eyJpIjoiZDY2NDQ2Zjc1NTMwNGVjMThjNjRmNzZiOWM3ZDA2ODMiLCJwIjoiaiJ9)
[CODE-3136]: https://codecovio.atlassian.net/browse/CODE-3136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

return statement lines details

---

codecov_cli/main.py
tests/commands/test_invoke_labelanalysis.py

now we can use `codecovcli {command} -h ` or `codecovcli {command} --help `

add -h for help

---

codecov_cli/services/upload/upload_sender.py
tests/helpers/test_upload_sender.py

Show a commit url or UI url to the user after uploading so it can take him directly to the codecov-app

log destination url for user when uploading

---

codecov_cli/commands/labelanalysis.py
tests/commands/test_invoke_labelanalysis.py

This change comes as a request of sentry infra team to increaase our chances of merging ATS into getsentry initially.
The `--dry-run` option simply stops label analysis after collecting labels and prints them in the terminal. Yes, there are
other ways that you can achieve the same result (e.g. custom runner), but this is more straight forward.
It might be marginally useful when setting up or building confidence of label analysis for customers interested in the feature,
so why not?
I decided to add a brief explanation to what each label group is, since we have that opportunity here.

Add dry-run to labelanalysis

---

codecov_cli/plugins/__init__.py
tests/plugins/test_instantiation.py

This PR implements a fix for the incorrect custom plugin path config field, by removing the incorrect field and replacing it with a field for the module and a field for class.
This PR also implements a fix for handling cases where the custom plugin params field is missing or empty.  
Fixes: #60

Fix custom plugin system config fields 

---

codecov_cli/services/empty_upload/__init__.py
tests/plugins/test_instantiation.py
tests/services/empty_upload/test_empty_upload.py

This logs out the result of the empty upload 
note: changes in  tests/plugins/test_instantiation.py are linting only

logging the result of the empty upload process

---

codecov_cli/services/staticanalysis/__init__.py
tests/services/static_analysis/test_static_analysis_service.py

This commit changes the static-analysis command in the CLI, such that it calls the staticanalysis/analyses/<external_id>/finish endpoint in the API after it uploads the necessary files. This endpoint schedules the static analysis task on the worker immediately.
Fixes: #66

Call static analysis finish endpoint after uploading files

---

requirements.in
setup.py

This PR pins the dependencies versions in setup.py. These dependency versions are generated by pip-compile.
This PR separates the dev dependencies into a separate dev.txt file. This file is generated by using the `pip-compile` command on the `dev.in` file.
This PR introduces a script to generate the list of dependencies in `requirements.txt` with  their versions pinned to be copied into the `setup.py` file.
This PR modifies the push GHA to use `dev.txt` instead of `requirements.txt` to install dependencies
Fixes: https://github.com/codecov/codecov-cli/issues/189

Pin dependencies in setup.py and separate dev deps

---

codecov_cli/runners/python_standard_runner.py
tests/runners/test_python_standard_runner.py
tests/services/static_analysis/test_static_analysis_service.py

Adds the coverage_root config option for PythonStandardRunner so users can override the `--cov=./` option.
Fixes [platform-team #77](https://github.com/codecov/platform-team/issues/77)

Allow users to change coverage root for python runner

---

codecov_cli/commands/upload_completion.py
codecov_cli/main.py
codecov_cli/services/upload_completion/__init__.py
tests/services/static_analysis/test_static_analysis_service.py
tests/services/upload_completion/test_upload_completion.py
tests/test_codecov_cli.py

creating new command that tells codecov that the user has finished uploading and now wants to get notifications - notifications is part of the api endpoint, not related to this change specifically 
side note: I feel that 'upload-completion' is not a very descriptive name to what we're trying to do here. Do you think we can name it in a more descriptive way? Let me know if you have better ones

Complete upload command

---

codecov_cli/runners/python_standard_runner.py
tests/runners/test_python_standard_runner.py

instead of using the result as a dictionary we can use it as the object we wrap it into.
There are 2 benefits to this:
1. It's cleaner to read
2. It does the fallback to `[]` if the api returns any of the values as `None`. This avoids a bug we saw yesterday when trying to concatenate list to None.
We do the wrapping in labelanalysis, before passing it to the runner.

Use `LabelAnalysisRequestResult` object

---

codecov_cli/commands/labelanalysis.py
tests/commands/test_invoke_labelanalysis.py
tests/services/static_analysis/test_static_analysis_service.py

These changes alter the way label analysis command works by making 2 requests to Codecov instead of 1.
Why would we want to do this, if it's more time to make a second request?
Because it takes (usually) longer to collect the labels than it takes to make a second request.
Specially for bigger repos, collecting the labels can take dozens of seconds.
By making the label collection parallel with the labels processing we can speed up the total ATS time.
We still PATCH the labels in case the worker hasn't finished the calculations, and it will
correctly refresh the request labels from the DB (based on [here](https://github.com/codecov/worker/pull/1210)).
However even if it misses the requested labels we recalculate the `absent_labels`, if needed (`_potentially_calculate_absent_labels`).
So we …

Send labels to Codecov only after collecting them

---

README.md

This PR adds a link to the contributing repo that contains the guidelines for working in the Codecov open source repo.

docs: Add Link to Contributing Repo

---

.github/workflows/push_flow.yml

Before adding ATS to the CLI we need to emit the static analysis info

push static analysis info of the CLI to codecov

---

codecov_cli/helpers/request.py
tests/helpers/test_request.py

Came across this while integrating this with the bazel stuff. Having the stacktrace in the user's terminal is annoying, so fixing it. 
Raising an exception prints out all stacktrace, which is not practical nor helpful. raising click.Exception only prints out the exception msg
before the change codecovcli create-commit gives the following: 
```
info - 2023-07-24 20:50:53,124 -- ci service found: local
Traceback (most recent call last):
File "/Users/dana/.pyenv/versions/cli-env-v2/bin/codecovcli", line 33, in <module>
sys.exit(load_entry_point('codecov-cli', 'console_scripts', 'codecovcli')())
File "/Users/dana/codecov/codecov-cli/codecov_cli/main.py", line 77, in run
cli(obj={})
File "/Users/dana/.pyenv/versions/3.10.5/envs/cli-env-v2/lib/python3.10/site-packages/click/core.py", line 1130, …
```

cleaner exception log

---

codecov_cli/services/upload/coverage_file_finder.py

Adding pylcov.dat to the list of coverage files to search for.

bazel creates lcov ceverage files with pylcov filename. 

---

codecov_cli/commands/labelanalysis.py
codecov_cli/runners/python_standard_runner.py

In particular we will now include the `external_id` of the label analysis request object (so it's easier to find in the logs),
and the processing errors that happened in label analysis task. So the user can better self-support.
I also moved the message about the labels to run from the python runner to the command in general because it's something the user would like to see in general.

Improve label analysis messages

---

README.md

Use cli.codecov.io instead of uploader.codecov.io as example for integrity checking the binary.
When I was integrating this CLI into our CI pipeline, I ran into this error that caused me lots of confusion, since I ended up copy/pasting from the documentation into my CI code. Hopefully this saves someone else the headache.

Fix integrity checking readme

---

.github/workflows/push_flow.yml
codecov.yml
codecov_cli/commands/upload.py
tests/commands/test_invoke_labelanalysis.py
tests/commands/test_invoke_upload.py
tests/commands/test_invoke_upload_process.py
tests/helpers/test_git.py

Changing tests that used the `-v` option (invoking the CLI) to instead use the fixture. This prevents tests from messing up the global env across tests when running pytest using ATS. As we've been discovering recently, it's a big mess sometimes.
The removal of "MASKED" from some git tests is because it was throwing errors in CI. Maybe it's a python 3.11.x thing... But I suppose they changed when the removal of secrets run. I changed for bogus secrets.
THe git services was also an error, so I had to put them in a list.

Enable ATS in the CLI

---

codecov_cli/commands/commit.py
codecov_cli/commands/create_report_result.py
codecov_cli/commands/empty_upload.py
codecov_cli/commands/get_report_results.py
codecov_cli/commands/report.py
codecov_cli/commands/upload.py
codecov_cli/commands/upload_completion.py
codecov_cli/commands/upload_process.py
codecov_cli/helpers/options.py
codecov_cli/services/report/__init__.py
codecov_cli/services/upload_completion/__init__.py
tests/commands/test_invoke_upload_process.py

- Creates options.py in commands/helpers
- Moves common options to global_options
- Adds global_options decorators to some subcommands
Fixes: https://github.com/codecov/codecov-cli/issues/208

Add fail-on-error flag to commands that were missing it

---

codecov_cli/services/upload/upload_collector.py

since worker doesn't accept empty reports, or not saving anything in the storage url, let the CLI raise an exception to the users when no coverage reports found

raise exception when no coverage reports found 

---

codecov_cli/commands/labelanalysis.py

When running ATS locally, it wasn't logging out the errors returned by the API

adding errors to extra_log_attributes

---

codecov_cli/commands/labelanalysis.py
codecov_cli/commands/staticanalysis.py

To make it easier for users to onboard ATS the CLI will look for the value of
static analysis token in the envvar CODECOV_STATIC_TOKEN.
This is similar to what we have for the upload token.
closes codecov/engineering-team#192

feat: add envvar for static analysis token

---

codecov_cli/commands/labelanalysis.py
codecov_cli/commands/staticanalysis.py
codecov_cli/helpers/validators.py
tests/commands/test_invoke_labelanalysis.py
tests/factory.py
tests/helpers/test_validators.py

This was motivated by the fact that api returns 404 if your label-analysis request
doesn't include a `base_commit` or a `head_commit`. I don't mean the key must be there,
the value needs to be an accurate value, or it will return a puzzling 404 "Not Found".
That is terrible user experience, and even I needed quite some time to figure it out.
So the best thing (I think) is cutting the evil in its root and making sure the user
gives us a valid SHA.
These changes introduce `validate_commit_sha` to `static-analysis` and `label-analysis` commands.
They make sure the user gives us a string that is 40 chars long and consists of only letters and
numbers. So should at least look like a SHA1 string.

feat: validate commit SHAs

---

codecov_cli/commands/send_notifications.py
codecov_cli/main.py
tests/test_codecov_cli.py

renaming upload-completion command to send-notifications, to follow the format of other cli commands
and to give it a more descriptive name. This command can be used whenever a user wants to trigger notifications in cases where no reports where uploaded, or didnt receive notifications for whatever reason. So it makes sense to rename it to be more notifications related than uploads 
We didn't receive any logs for the task that gets triggered except from our repos so it's safe to rename it

renaming upload-completion command to send-notifications

---

codecov_cli/services/upload/upload_collector.py

This is causing issues where files fail to open because the call is using the wrong encoding

Change encoding of open in _get_file_fixes to utf8

---

codecov_cli/services/staticanalysis/analyzers/javascript_es6/node_wrappers.py
samples/inputs/sample_004.js
samples/outputs/sample_004.json

We had a call with a customer trying ATS today and they had an error in the JS analyser.
The error was "first_statement referenced before assignment".
This would happen if the first statement in a `do-while` block was not a `statement_block` or `expression_statement`
(I added this case in `sample_004.js` to test it)

fix: JS analyser do-statement

---

codecov_cli/services/upload/upload_collector.py
tests/data/files_to_fix_examples/bad_encoding.go
tests/services/upload/test_upload_collector.py

Don't want to crash when there's a decoding error when trying to apply file fixes, want to log warning that file fixes could not be applied to the file and provide information about decoding error.

Handle error reading code files for file fixes due to decoding error

---

codecov_cli/helpers/config.py
codecov_cli/main.py
tests/commands/test_invoke_labelanalysis.py
tests/commands/test_invoke_upload_process.py
tests/services/empty_upload/test_empty_upload.py

Adding `codecov.yml` as the default config file the CLI will look for.
It's easy for users to forget to add that in the command, and have it misconfigured and then be like
"why is this not working?".
It's also likely that they'll put the config in the codecov.yml where the rest of they codecov config already lives.
context codecov/engineering-team#397

chore: add default config

---

codecov_cli/runners/python_standard_runner.py

fixes https://github.com/codecov/engineering-team/issues/449
example output
```
info - 2023-09-12 17:21:51,277 -- Received information about tests to run --- {"absent_labels": 6, "present_diff_labels": 0, "global_level_labels": 0, "present_report_labels": 0}
info - 2023-09-12 17:21:51,277 -- Running tests. (run in verbose mode to get list of tests executed)
info - 2023-09-12 17:21:51,277 --   pytest options: "--cov=app --cov-context=test"
info - 2023-09-12 17:21:51,277 --   executed tests: 6
...
info - 2023-09-12 17:21:52,312 -- Finished running 6 tests successfully
info - 2023-09-12 17:21:52,312 --   pytest options: "--cov=app --cov-context=test"
```

fix: add prettier pytest logging

---

codecov_cli/runners/python_standard_runner.py
tests/runners/test_python_standard_runner.py
tests/runners/test_runners.py

The `include_curr_dir` option is only for strict_mode in python standard runner.
Few people will ever use the strict mode.
Realistically, no one will ever make `include_curr_dir` False because it increases the change
that ATS won't work (and it doesn't work on enough siturations to add one more).
I'm keeping the `strict_mode`, but making the `include_curr_dir` always True.
The default was already True, but now there's no choice.

chore: remove include_curr_dir option

---

codecov_cli/commands/labelanalysis.py
codecov_cli/runners/python_standard_runner.py
codecov_cli/runners/types.py
tests/commands/test_invoke_labelanalysis.py
tests/factory.py
tests/runners/test_python_standard_runner.py
tests/runners/test_runners.py

This makes the --dry-run in label-analysis actually do something useful.
It prints the tests you need to run _with_ the tool options to make ats run correctly.
In the case of pytest this means that it prints `--cov-context=test` (we need this to get labels)
and then the list of labels to run, spearated by spaces.
I couldn't find a way to actually export an ENV variable safely so I'm just printing to stdout
The small problem is that there's other output with it, so I decided to add "ATS_TESTS_TO_RUN="
to make grep-ing easier. Just for good measure throw it in a file as well.
So in thory if you get ATS_TESTS_TO_RUN from your CI you can do
`pytest <YOUR NORMAL OPTIONS> <ATS_TESTS_TO_RUN>` and that should work to run all the ATS tests.
closes codecov/engineering-team#470

fix: make --dry-run useful

---

codecov_cli/services/staticanalysis/analyzers/general.py
samples/inputs/sample_002.py
samples/outputs/sample_002.json

context: codecov/codecov-cli#243
User ran into `RecursionError: maximum recursion depth exceeded` running
`_get_max_nested_conditional`.
By removing the recursion from the function we hopefully fix this issue.
So now it's using text-book definition of BFS to go about finding the max depth.
Notice we do have to go through all nodes of the function because we don't know if a node that is not
of type conditional doesn't have another conditional inside of it (think block nodes, for example).
And we only increase the level when we pass through one conditional, not when we go to the next child.
close codecov/codecov-cli#243

fix: make max_conditional iterative

---

codecov_cli/commands/labelanalysis.py

https://github.com/codecov/worker/pull/99 had the unwanted and overlooked effect of slightly changing the format
of the response from Codecov label-analysis.
Before the "errors" key was inside the "result" (it shouldn't be)
So the CLI is not surfacing these errors anymore.
These changes fix that and move the log line to a more logical position.

fix: surface processing errors

---

codecov_cli/main.py

This commit fixes the following error discovered
when trying to run the latest executable:
File "codecov_cli/main.py", line 23, in <module>
ImportError: attempted relative import with no known parent package

Fix relative import error on import __version__

---

codecov_cli/services/staticanalysis/analyzers/python/node_wrappers.py
samples/inputs/sample_005.py
samples/outputs/sample_005.json
tests/services/static_analysis/test_analyse_file.py

context: https://l.codecov.dev/hfGkNI
This is a fix for a bug that I stumbled upon today.
After much investigation it boils down to this:
- treesitter count's docstrings as strings, not comments (which is to be expected I suppose)
- pytest counts them as comments. They won't appear in the coverage report (if function docstring)
- if you select a docstring as the line of surety ancestorship, because it's not in the report, it has
no labels associated with it, so ATS selects no tests for that line
We were doing that (I believe) and selected a function docstring as the line in base to look for tests.
No tests were found, and so ATS passed, but all tests failed.
These changes fix this behavior by doing 2 things:
1. Making sure function docstrings are not in `statements` on the static analysis …

fix: Fix python analysis for function docstrings

---

codecov_cli/services/staticanalysis/__init__.py
codecov_cli/services/staticanalysis/analyzers/__init__.py
codecov_cli/services/staticanalysis/analyzers/python/__init__.py
codecov_cli/services/staticanalysis/analyzers/python/node_wrappers.py
tests/services/static_analysis/languages/python/test_node_wrappers_malformed_code.py
tests/services/static_analysis/test_static_analysis_service.py

This was needed already.
But ultimately inspired by a user tha had the following error:
```
File "codecov_cli/services/staticanalysis/analyzers/python/node_wrappers.py", line 41, in do_visit
first_if_statement = first_if_statement.children[0]
IndexError: list index out of range
```
Despite my best efforts, I was only able to reproduce this error using invalid Python code
(i.e. an empty `if` statement)
Regardless of what caused this issue in the 1st place, there may be valid reasons
for someone to have malformed code in their repo (depending what the repo is 👀)
So we should be able to still upload _something_ and ignore the failures.
The tricky thing here is that without the static analysis data ATS can't work well.
And we can't be sure that the analyzer doesn't have bugs. I don't think …

fix: better handle errors in static analysis

---

codecov_cli/commands/labelanalysis.py
tests/commands/test_invoke_labelanalysis.py

related to codecov/engineering-team#555
These changes update the output of `--dry-run` option so that:
1. Users can get a list of tests that are being skipped
2. Users have the option to parse the output from JSON
> ⚠️
>
>  The JSON output doesn't include the runner options in the tests to run list.
>  Instead there's the 'runner_options' key with that info.
>  This is to make sharding the list of tests easier
It's considerably more output, but given that we don't have clear guidelines on the
best way to do things I think it's better to provide all options.
Eventually adoption will converge to some way or another and we prioritize that.

Update --dry-run output

---

codecov_cli/commands/upload.py
codecov_cli/commands/upload_process.py
codecov_cli/services/upload/__init__.py
codecov_cli/services/upload/upload_collector.py
tests/commands/test_invoke_upload_process.py
tests/services/upload/test_upload_collector.py

since node uploader supports turning file fixes off, we're doing it here too. 
https://github.com/codecov/engineering-team/issues/556
slack discussion for further context https://l.codecov.dev/RQNTLl

disable file fixes

---

codecov_cli/__init__.py

The path for the version file was not currectly setup.
It was looking for VERSION in the current dir (where python was running),
not where the CLI is installed.

fix: Fix VERSION file missing

---

codecov_cli/__init__.py
setup.py

this is the minimum patch to fix building from source
tested with `python -m build`
I also added `python_requires` so that older pythons will get a useful error message if attempting to install an incompatible version

ref: fix version lookup and package build from source

---

codecov_cli/commands/labelanalysis.py
codecov_cli/runners/__init__.py
codecov_cli/runners/pytest_standard_runner.py
tests/runners/test_pytest_standard_runner.py
tests/runners/test_runners.py

This is lower priority, but it has been pointed out to me that `PythonStandardRunner`
is not accurate. There are other test runners available in python after all.
So these changes simple rename it to be `PytestStandardRunner` instead.
Include changes to default options to the `--runner` option and the config key
for the runner. I made that to be backwards compatible tho.

chore: rename PythonStandardRunner

---

codecov_cli/services/staticanalysis/__init__.py

This is an attempt to limit the httpx.PoolTimeout
errors when uploading code.
Fingers crossed the default limits work better for us.
Let it be known that we don't know why the limits were chosen,
so we are essentially winging it at this point.

fix: Try to fix httpx.PoolTimeout error

---

codecov_cli/services/staticanalysis/__init__.py

This is more a fix around error handling and updating information to users than actual performance.
**Error Handling**
In terms of error handling, consider that the number of uploads is too big. We "start" all of them at the same time, but the number of connections is limited.
For uploads you stringify the data and try to grab a connection from the pool to upload. Then you need to _actually_ upload (e.g. write data to the pipe)
Some timeouts can exist in this process:
* `PoolTimeout` - waiting too long for a connection to become available
* `ReadTimeout` - waiting too long for a response back (these are the most important ones)
Given that we _will_ have thousands of files to upload it _will_ take a long time, but that's alright. So we can simply ignore those timeouts.
Then we need to …

fix: Make static analysis handle a large number of uploads

---

.gitignore
codecov_cli/commands/labelanalysis.py
codecov_cli/helpers/request.py
codecov_cli/services/report/__init__.py
codecov_cli/services/staticanalysis/__init__.py
tests/helpers/test_request.py

add `User-Agent: codecov-cli/{version}` header to outgoing requests so we can track CLI usage by version / compare against gazebo or node uploader volume
`requests` also has a `Session` object that lets us set persistent headers, we could also create one of those and plumb it through the code somehow or save it as a global. lmk if that's preferred
https://docs.python-requests.org/en/latest/user/advanced/#session-objects

feat: add user agent to all requests

---

codecov_cli/services/upload/upload_sender.py
tests/helpers/test_upload_sender.py

Fixes: https://github.com/codecov/codecov-cli/issues/207
Depends on: https://github.com/codecov/worker/pull/58

Change path_fixes to report_fixes

---

.github/workflows/ci.yml
codecov_cli/commands/labelanalysis.py
tests/commands/test_invoke_labelanalysis.py

label-analysis was build to be dependable. Even if the calculation fails (which is rare)
we have many fallback systems in place, so that you can add the label analysis step before
tests and make sure the tests will run.
The fallbacks come with a price, though: running all tests.
One thing we don't do so well is surfacing when label-analysis fallback in a way customers can
use to help build their confidence in label-analysis.
We do have logs that point out that something was not successful and that we tried to fallback.
Sentry specifically requested that we also surface this information in the dry-run output.
These changes do that, letting users check the dry-run output if label-analysis had to
fallback, and if so, what was the reason for it.
(only for JSON tho, because space-separated …

feat: surface label-analysis fallbacks

---

codecov_cli/plugins/compress_pycoverage_contexts.py
requirements.txt
setup.py

We want to add codecov-cli to getsentry/pypi.
It was asked that we drop the smart-open dependency.
I went back and checked that smart-open is really used for dealing with
files in remote storage and decompressing things under-the-hood.
We don't need any of that, and are well served by the default open function.
So it's fine to drop it.

chore: remove smart-open

---

codecov_cli/commands/labelanalysis.py
tests/commands/test_invoke_labelanalysis.py

Since the previous change to label analysis the help text was outdated.
These changes fix it to be more accurate.
Also removing the test for the help text because it's more annoying than
it's helpful. It doesn't really _test_ anything, because the formatting
is done by click

chore: Fix helper text in label analysis

---

codecov_cli/helpers/encoder.py
codecov_cli/helpers/git.py
codecov_cli/helpers/git_services/github.py
codecov_cli/services/commit/__init__.py
codecov_cli/services/upload/upload_sender.py
tests/helpers/git_services/test_github.py
tests/helpers/test_encoder.py
tests/helpers/test_git.py
tests/services/commit/test_commit_service.py

This is the first PR for tokenless upload and branch conflation bug fix where we check if the PR is a fork PR. 
I'm not using any auth tokens as forked PRs are public for open source repos. And a forked repo made from a public upstream cannot change its visibility to private. 
This PR implements getting PR info from github only, other providers are needed still, but pushing my code to get initial review 
We'll need to add the fork PR check in each command we want to support tokenless for. For uploads we'll need to add it to create_commit, create_report and do_upload commands logic. But, create_report does not have reference to the PR number, which means we'll need to add it there. 
https://github.com/codecov/engineering-team/issues/733

check if the PR is a fork PR

---

codecov_cli/commands/report.py
codecov_cli/services/report/__init__.py
tests/helpers/git_services/test_github.py
tests/services/commit/test_commit_service.py
tests/services/report/test_report_service.py

we need the pr number for the PR API request to know if the command runs in a fork PR

adding PR option to create-report command 

---

codecov_cli/helpers/git.py
codecov_cli/services/commit/__init__.py
codecov_cli/services/report/__init__.py
codecov_cli/services/upload/upload_sender.py
tests/helpers/test_git.py
tests/services/commit/test_commit_service.py

- taking get_pull out of is_fork_pr for usability. I don't think it's the responsibility of is_fork_pr to do the request and get the pull's information 
- overriding branch in commit's endpoint since that's the only command that actually uses it and sends it in part of the request.

amend branch names to be forked-slug:branch-name

---

codecov_cli/services/upload/upload_collector.py

If lineno is unset that means that the file is empty thus the eof should be 0, so lineno will be -1.
Fixes: https://github.com/codecov/codecov-cli/issues/320

Fix lineno being unset

---

codecov_cli/helpers/git.py
codecov_cli/helpers/git_services/__init__.py
codecov_cli/helpers/git_services/github.py
codecov_cli/services/commit/__init__.py
codecov_cli/services/report/__init__.py
codecov_cli/services/upload/upload_sender.py
tests/services/commit/test_commit_service.py

Public forks will accept tokenless uploads.
Currently we were just sending an empty header (no Authorization). These changes add a header `X-Tokenless: fork_slug` so we know easily that the request is from a fork, and which fork it's from.
I also have a tendency to compulsively add typehints to complex types.

add X-Tokenless header when uploading from fork

---

codecov_cli/runners/pytest_standard_runner.py
tests/runners/test_pytest_standard_runner.py

We add 'pytest_command' so that users can specify the pytest command to use. That is still confusing for users to setup the config. Plus people are more used to give a python path to execute.
So I think it's good idea to replace 'pytest_command' to the simpler 'python_path'.

chore: rename 'pytest_command' to 'python_path'

---

codecov_cli/commands/labelanalysis.py
codecov_cli/runners/__init__.py
codecov_cli/runners/pytest_standard_runner.py
tests/commands/test_invoke_labelanalysis.py
tests/runners/test_pytest_standard_runner.py
tests/runners/test_runners.py

context: codecov/engineering-team#407
Consider this a 1st iteration of this feature.
A compromise between "this is easy to implement and helpful to users" and "users don't have to think to use this".
The benefit is that now you can add dynamic params to your runners, the downside is that you need to know the runner configuration AND format these params accordingly.
Otherwise it would be very hard to figure out exactly what parameter group a given parameter is. So, compromise.
More details on whoe to actually use the feature are documented in the code.

feat: dynamic runner parameters

---

codecov_cli/helpers/versioning_systems.py
tests/helpers/test_folder_searcher.py
tests/helpers/test_versioning_systems.py

Parsing of output of the `ls-files` commands was splitting paths with spaces. It is literally the difference show below.
```python
>>> s = 'string space\nother line\n'
>>> s.split()
['string', 'space', 'other', 'line']
>>> s.split('\n')
['string space', 'other line', '']
```
closes: codecov/codecov-cli#356

fix: correctly generate network if path has spaces

---

.github/workflows/ci.yml

we don't want to run the steps in the CI workflow that require access to secrets so that they don't block the tests from running.

build: don't run steps that req secrets if fork

---

codecov_cli/helpers/config.py
codecov_cli/main.py
samples/fake_project/codecov.yml
tests/helpers/test_config.py

fixes https://github.com/codecov/codecov-cli/issues/365
the node uploader [searched for a codecov yaml in one of 12 paths](https://github.com/codecov/uploader/blob/1e505ba8a27a1e3311a7a8db7f314e3705a2ee08/src/helpers/token.ts#L69-L76). this PR searches the same 12 paths when looking for the codecov yaml on startup

fix: search acceptable paths for codecov yaml if not passed in

---

codecov_cli/helpers/request.py

related to: https://github.com/codecov/codecov-cli/issues/370

fix: use sys.exit() instead of just exit()

---

codecov_cli/plugins/__init__.py
tests/plugins/test_instantiation.py

context: https://github.com/codecov/feedback/issues/258
Currently there's no way to disable plugins.
We don't want to change the default to preserve compatibility with the uploader little magic tricks that were executed by default (as far as I know).
These changes allow you to pass the `--plugin noop` option to the `create-upload` command in order to not execute any plugin.

feat: make noop plugin recognizable

---

.github/workflows/ci.yml

Uploads test results to codecov

build: upload test results

---

codecov_cli/main.py

just want to quickly solve this: https://github.com/codecov/feedback/issues/259, I don't think we can use `typing.Optional` in either the `type` field in the `click.option` decorator or the `path_type` field in the `click.Path` class

fix: remove typing.Optional from codecov yaml path option

---

codecov_cli/services/upload/file_finder.py
tests/services/upload/test_coverage_file_finder.py

fixes https://github.com/codecov/feedback/issues/84
This PR does 3 things
1. Rename `project_root` to `search_root` to make it more maintainable and understandable
2. Remove the restriction on certain folders when searching for a user-given string. **Unknown**: how this may affect performance for large repositories. Would love insight here, but it shouldn't degrade that poorly. It's all `os.walk`
3. Compare the user resolved paths to resolved found paths. This is an apples to apples match which would fail beforehand if the user didn't give full pathing (vs relative to root)

fix: update user file search

---

codecov_cli/helpers/versioning_systems.py
tests/helpers/test_versioning_systems.py
tests/services/upload/test_coverage_file_finder.py

Apparently a common thing for CIs to do is create a merge-commit for changes
in a branch before running tests and stuff.
This means that - especially for not-directly-supported CIs - we would maybe
return a SHA for a commit that didn't exist in the branch.
These changes fix that by checking to see if the current commit is a merge commit.
If it is we return the second parent, the most recent commit before the current one.
Q: What if the current latest commit in the branch is a merge commit?
Well in this case the parent, which is also part of the branch, will have the coverage.
Users can still provide a commit sha value to override this behavior.
closes codecov/codecov-cli#372

fix: better detect merge-commits

---

README.md
codecov_cli/helpers/versioning_systems.py

Hi, I'm not a python person so not sure best way to add test coverage for this, but to kick off a discussion here's the code change.
We run our CI through Jenkins, and to support job fanout our build process involves doing a git checkout on one node, caching the application files, and then subsequent nodes will restore code from that cache and run a subset of our tests. (We currently have a job fanout of around 50.) To reduce the size of the cached blob, we are excluding our .git folder from the cache.
This leads to us hitting a problem uploading our coverage files, because the GitVersioningSystem:
- says it `is_available` if git is installed on the system (which it is because we reuse our worker base images)
- in `get_network_root` it fails because `git rev-parse --show-toplevel` is …

Fix compatibility on non-git project folders when git is installed on the system

---

codecov_cli/services/upload/upload_collector.py

chore: improve error message for finding reports

---

codecov_cli/services/upload/upload_sender.py
tests/helpers/test_upload_sender.py

Fixes: https://github.com/codecov/engineering-team/issues/1297

fix: add ci_service to upload data

---

codecov_cli/helpers/folder_searcher.py
codecov_cli/helpers/git_services/github.py
codecov_cli/helpers/request.py
codecov_cli/helpers/versioning_systems.py
codecov_cli/services/staticanalysis/analyzers/general.py
codecov_cli/services/upload/upload_collector.py

fixes https://github.com/codecov/codecov-action/issues/1303
`git ls-files` will pull submodules as files, this change just logs that a file shows up as such a directory and continues on

fix: log info if a file shows up as a directory

---

codecov_cli/services/upload/file_finder.py
tests/services/upload/test_coverage_file_finder.py

fixes https://github.com/codecov/codecov-action/issues/1379

fix: allow for .. explicit file search

---

codecov_cli/helpers/ci_adapters/__init__.py
codecov_cli/helpers/ci_adapters/cloudbuild.py
tests/ci_adapters/test_cloudbuild.py

Add Google Cloud Build CI detection and build meta-data extraction from the environment variables when they are mapped.
Google Cloud Build uses [variable substitutions](https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values) in the builds and not environment variables.
It is possible to map substitution variables to environment variables in the builds, but it has to be done [manually](https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values#map_substitutions_manually).
For this CI adapter to work, these variables needs to be mapped:
```
env:
- '_PR_NUMBER=$_PR_NUMBER'
- 'BRANCH_NAME=$BRANCH_NAME'
- 'BUILD_ID=$BUILD_ID'
- 'COMMIT_SHA=$COMMIT_SHA'
- 'LOCATION=$LOCATION'
- 'PROJECT_ID=$PROJECT_ID'
- 'PROJECT_NUMBER=$PROJECT_NUMBER'
- …
```

feat: add Google Cloud Build CI support

---

.github/workflows/ci.yml
codecov_cli/helpers/ci_adapters/codebuild.py

This adds basic support for python 3.12:
- An unescaped `\` now [raises a SyntaxWarning](https://docs.python.org/3/whatsnew/3.12.html#other-language-changes)
- Since 3.12 [removed setuptools](https://docs.python.org/3/whatsnew/3.12.html#ensurepip), `python setup.py` will fail to import setuptools. Note that directly executing setup.py has been [unofficially deprecated/discouraged](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/) for a while, so I've updated to use `pip` instead (there are other places as well but those might take more work)

support python 3.12

---

setup.py

Release PR for 0.7.1
I've updated the version name and committed: 3e4611f76735ae3b5fac8e82300a14c694298eba.

Release 0.7.1

---

codecov_cli/main.py
tests/commands/test_upload_token_discovery.py

Just like in the old days... Before this patch, the v4-related rewrite of the Codecov uploader CLI lost the ability to use the token set in the config file [[1]]. This change fixes the regression recovering the original behavior.
The bug has been discovered during the re-configuration of ``codecov/codecov-action`` in ``pytest-dev/pytest``. We use the clear-text token to improve stability of uploads in PRs from forks so it makes sense to keep it in the config rather than in the GitHub Actions CI/CD definition file.
[1]: https://docs.codecov.com/docs/codecovyml-reference#codecovtoken

🐛 Use config-set token as CLI default fallback

---

codecov_cli/helpers/folder_searcher.py
codecov_cli/services/upload/file_finder.py
tests/ci_adapters/test_azure_pipelines.py
tests/commands/test_process_test_results.py
tests/helpers/test_git.py
tests/helpers/test_network_finder.py
tests/helpers/test_request.py
tests/helpers/test_upload_sender.py
tests/services/empty_upload/test_empty_upload.py
tests/services/report/test_report_service.py
tests/services/static_analysis/test_static_analysis_service.py
tests/services/upload/test_coverage_file_finder.py
tests/services/upload/test_upload_service.py

This fixes a bunch of typing errors, as well as auto-reformats a bunch of stuff via the precommit hook.

Slightly improve `FileFinder` typing

---

.github/workflows/ci.yml

Update the CI to aggregate results all into one comment. This will be useful for extracting into its own action in the future.
Basically, changes needed to ensure one comment:
- test junit.xml files are exported to an artifact of some `${UNIQUE_IDENTIFIER}junit.xml`
- an "aggregation" job that puts all the `*junit.xml` files into a directly
- calling process_test_results with the dir with all the junit files
I've added a breaking test for testing purposes. Once I get an approval, I'll remove it.

Aggregate the test results files in CI

---

setup.py

Release PR for 0.7.5
I've updated the version name and committed: 7e72c6397d5288ea407f166f16681baf5abd9698.

Release 0.7.5

---

.github/workflows/ci.yml

We don't want this to run when merging. So, check that the Github Ref is available before running the command.
Sample error: https://github.com/codecov/codecov-cli/actions/runs/11075241131/job/30775783343

Only run test results parser for PRs

---

README.md

Better formatting of options for the `empty-upload` command

Better formatting of options for the `empty-upload` command

---

codecov_cli/services/commit/__init__.py
tests/services/commit/test_commit_service.py

depends on: https://github.com/codecov/codecov-action/pull/1511
fixes: https://github.com/codecov/engineering-team/issues/2065

fix: accept tokenless value from branch instead of env var

---

codecov_cli/services/commit/__init__.py

The fstring was missing the f prefix.

fix: log message was not rendered

---

.github/workflows/build_assets.yml
.github/workflows/build_for_pypi.yml
.github/workflows/ci.yml
codecov_cli/commands/upload_coverage.py
codecov_cli/helpers/ci_adapters/azure_pipelines.py
codecov_cli/main.py
codecov_cli/opentelemetry.py
codecov_cli/plugins/__init__.py
codecov_cli/plugins/compress_pycoverage_contexts.py
codecov_cli/plugins/gcov.py
codecov_cli/plugins/pycoverage.py
codecov_cli/plugins/xcode.py
codecov_cli/runners/pytest_standard_runner.py
codecov_cli/services/upload/file_finder.py
codecov_cli/services/upload/legacy_upload_sender.py
codecov_cli/services/upload/upload_collector.py
codecov_cli/services/upload/upload_sender.py
requirements.txt
setup.py

This also does a few other things:
1. Creates a `universal2` binary from our side to be compatible with `x86_64` and `arm64` macos builds
2. Removes `3.8` and adds `3.13` support

feat: add telemetry

---

.github/workflows/build_for_pypi.yml
setup.py

fixes https://github.com/codecov/codecov-cli/issues/570

fix: change name to codecov_cli for PEP625

---

.github/workflows/broadcast_api_changes.yml
.github/workflows/ci.yml
codecovcli_commands

fixes https://github.com/codecov/infrastructure-team/issues/486

feat: make a new issue

---

codecov_cli/helpers/request.py
tests/helpers/test_request.py
tests/helpers/test_upload_sender.py

fixes https://github.com/codecov/codecov-action/issues/1547

fix: add log for url on retry failure

---

codecov_cli/services/upload/file_finder.py

Hey! I was trying to exclude files from my upload with `codecovcli -v upload-coverage -d --exclude tests` and I got the following error:
```py
Traceback (most recent call last):
File "/home/tabulate/src/squiid-bindings/venv/bin/codecovcli", line 8, in <module>
sys.exit(run())
~~~^^
File "/home/tabulate/src/squiid-bindings/venv/lib/python3.13/site-packages/codecov_cli/main.py", line 93, in run
cli(obj={})
~~~^^^^^^^^
File "/home/tabulate/src/squiid-bindings/venv/lib/python3.13/site-packages/click/core.py", line 1161, in __call__
return self.main(*args, **kwargs)
~~~~~~~~~^^^^^^^^^^^^^^^^^
File "/home/tabulate/src/squiid-bindings/venv/lib/python3.13/site-packages/click/core.py", line 1082, in main
rv = self.invoke(ctx)
File "/home/tabulate/src/squiid-bindings/venv/lib/python3.13/site-package …
```

Fix crash with tuple concatenation onto list

---

codecov_cli/helpers/folder_searcher.py
codecov_cli/helpers/glob.py

fixes https://github.com/codecov/codecov-action/issues/1582
fixes https://github.com/codecov/codecov-action/issues/1728

fix: copy over globs translate

---

.github/workflows/release_flow.yml
codecov_cli/helpers/versioning_systems.py
codecov_cli/services/upload/network_finder.py
codecov_cli/services/upload/upload_collector.py
tests/factory.py
tests/services/upload/test_upload_collector.py

when the versioning system is `None`, `list_relevant_files` returns `None` so this changes the code in the upload_collector and the network_finder to handle that case
Fixes: https://github.com/codecov/codecov-cli/issues/641

fix: len(None) bug

---

codecov_cli/commands/labelanalysis.py
codecov_cli/commands/staticanalysis.py
codecovcli_commands

As a first step, this just hides the commands from help output, and marks them as deprecated, which means invoking them outputs a message saying so.

Hide and mark ATS-related commands as deprecated

---

.github/workflows/ci.yml
codecov_cli/commands/process_test_results.py
codecov_cli/helpers/folder_searcher.py
codecov_cli/helpers/versioning_systems.py
codecov_cli/plugins/xcode.py
codecov_cli/services/upload/file_finder.py
codecov_cli/services/upload/legacy_upload_sender.py
codecov_cli/services/upload/upload_sender.py
codecov_cli/types.py
tests/helpers/test_args.py
tests/helpers/test_folder_searcher.py
tests/helpers/test_legacy_upload_sender.py
tests/helpers/test_upload_sender.py
tests/plugins/test_xcode.py
tests/services/static_analysis/test_analyse_file.py
tests/services/upload/test_upload_collector.py
tests/test_types.py

This adds Windows and macOS to our CI test matrix.
It also changes quite a lot of internal functionality and tests to use `Path.as_posix()` which always prints paths with forward slashes.
This was primarily done to make a ton of tests work on Windows, but IMO it is also a good idea to normalize paths internally to use forward slashes.
---
As https://github.com/codecov/codecov-cli/pull/661 is primarily an issue on Windows, it would be nice to run tests on Windows as well.
And also macOS as well, why not. This should cover the major OSs that folks will be running in their own CI jobs that are using the CLI.

Test on all OSs

---

codecov_cli/helpers/versioning_systems.py
codecov_cli/services/upload/upload_collector.py
tests/data/Контроллеры/Пользователь/ГлавныйКонтроллер.php
tests/helpers/test_versioning_systems.py
tests/services/upload/test_upload_collector.py

This adds the `git ls-files` which instructs git to output files separated by `\0`, and otherwise output filenames verbatim without any special encoding.
The second fix is related to enforcing `utf-8` encoding when reading in file contents in order to produce "file fixes".
---
Fixes https://github.com/codecov/codecov-cli/issues/489, fixes https://github.com/codecov/codecov-action/issues/1550, fixes https://github.com/codecov/codecov-action/issues/1539

Fix handling files with unicode names or contents

---

README.md
codecov_cli/commands/create_report_result.py
codecov_cli/commands/get_report_results.py
codecov_cli/commands/report.py
codecov_cli/commands/upload.py
codecov_cli/main.py
codecovcli_commands
tests/commands/test_invoke_upload_coverage.py
tests/commands/test_invoke_upload_process.py

This hides all related commands and options from the docs, and removes mentions of them from the README.

Deprecate "local upload" related commands
