codecov_cli/services/upload/upload_sender.py
When testing ATS in the sentry fork I have 3 out of 5 uploads timing out when pushing to storage.
I noticed that we are generating the PUT payload *after* receiving the response from Codecov. Generating PUT payload includes compressing the report file, that might be pretty big, and considering that the pre-signed put URL has a TTL of 10s this time might be influential.
So now we are just prepping the data completely before starting the upload process, in the hopes that this will save us enough time to get all uploads into storage in time.
=> Encode PUT data before sending POST request to Codecov

codecov_cli/services/staticanalysis/analyzers/__init__.py, codecov_cli/services/staticanalysis/analyzers/general.py, codecov_cli/services/staticanalysis/analyzers/javascript_es6/__init__.py, codecov_cli/services/staticanalysis/analyzers/python/__init__.py, samples/inputs/sample_003.js, samples/outputs/sample_003.json
These changes include: 
- create a BaseAnalyzer that has all common functions between all analyzers 
- create a folder that has all JS analyzer logic 
- add complexity metrics to JS functions and methods. Note here that JS define methods in a different format than functions. So we have to search for both. When Python treats both the same 
- Add a more detailed test 
- edit functions names to add class or functions wrappers
Ticket: [CODE-3136](https://codecovio.atlassian.net/browse/CODE-3136?atlOrigin=eyJpIjoiOTIyNDFmMTdhOWY0NGE1Y2JmMWYxZDZlNzkxNTdjMDYiLCJwIjoiaiJ9)
[CODE-3136]: https://codecovio.atlassian.net/browse/CODE-3136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> JS analyzer improvements 

README.md
1- pip install codecov-cli instead of pip install codecovcli
2- some misspelling words
=> Fix read-me

codecov_cli/commands/base_picking.py, codecov_cli/commands/commit.py, codecov_cli/commands/create_report_result.py, codecov_cli/commands/empty_upload.py, codecov_cli/commands/get_report_results.py, codecov_cli/commands/labelanalysis.py, codecov_cli/commands/report.py, codecov_cli/commands/staticanalysis.py, codecov_cli/commands/upload.py, codecov_cli/helpers/config.py, codecov_cli/main.py, codecov_cli/services/commit/__init__.py, codecov_cli/services/commit/base_picking.py, codecov_cli/services/empty_upload/__init__.py, codecov_cli/services/report/__init__.py, codecov_cli/services/staticanalysis/__init__.py, codecov_cli/services/upload/__init__.py, codecov_cli/services/upload/legacy_upload_sender.py, codecov_cli/services/upload/upload_sender.py, tests/services/commit/test_base_picking.py, tests/services/commit/test_commit_service.py, tests/services/empty_upload/test_empty_upload.py, tests/services/report/test_report_results.py, tests/services/report/test_report_service.py, tests/services/static_analysis/test_static_analysis_service.py, tests/services/upload/test_upload_service.py
Ticket: [CODE-3311](https://codecovio.atlassian.net/browse/CODE-3311?atlOrigin=eyJpIjoiODNjMGU4MTM5OTBmNDlmYmE5ZDE3YmUwMDJhYjg5ZGQiLCJwIjoiaiJ9)
[CODE-3311]: https://codecovio.atlassian.net/browse/CODE-3311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> add --url use to all commands available

codecov_cli/commands/labelanalysis.py, tests/commands/test_invoke_labelanalysis.py
check if base sha and head sha are the same
=> do not run label analysis unless head and base shas are different

codecov_cli/helpers/folder_searcher.py, tests/services/upload/test_coverage_file_finder.py
This adds tests for searching for files from users input
=> Add unit tests for --file option

codecov_cli/services/upload/coverage_file_finder.py
When reviewing the ignore paths in the Node uploader, I found a few that weren't present here. I've updated the file and folder ignore paths to rectify this.
=> Add new ignore paths

codecov_cli/services/upload/upload_sender.py, tests/helpers/test_upload_sender.py
Depends on: https://github.com/codecov/codecov-api/pull/31
=> Add version to upload request data

codecov_cli/services/upload_completion/__init__.py, tests/services/upload_completion/test_upload_completion.py
Response's dict doesn't have result in it. Logging out all response
=> log out response correctly

README.md
=> add --disable-search to docs

codecov_cli/runners/python_standard_runner.py, tests/runners/test_python_standard_runner.py
There are options that only make sense when running tests (i.e. reporting),
and people use them. So we need to support those as well.
Still no checks there, so the user uses them at their own risk.
Except for the `--cov` option that we are checking to avoid issues, because we do set that one.
So I added a check for it, and we emit a warning message if we find it, but
make no changes.
closes codecov/engineering-team#191
=> feat: add support for options when running tests

codecov_cli/commands/empty_upload.py, codecov_cli/services/empty_upload/__init__.py, tests/services/empty_upload/test_empty_upload.py
This is causing an error due to missing parameter
=> empty upload is missing a parameter

codecov_cli/main.py
fixes https://github.com/codecov/codecov-cli/issues/185
=> fix: explicitly import version so click doesnt have to find it

setup.py
Release PR for 0.3.8
I've updated the version name and committed: 8e1cbc97237fb6cdf9dea46d229cf451f3b8a5e9.
=> Release 0.3.8

setup.py
Release PR for 0.4.1
I've updated the version name and committed: 15f5a06231b23c0252c31c34b0ca9a2cc2a0eafd.
=> Release 0.4.1

setup.py
Release PR for 0.4.2
I've updated the version name and committed: 47aa664128db4bff00de149d410d401a2b9d19ab.
=> Release 0.4.2

setup.py
Release PR for 0.4.3
I've updated the version name and committed: 1e4964397592de4d45e9cd8681634ea9ca7605a0.
=> Release 0.4.3

setup.py
Release PR for 0.4.5
I've updated the version name and committed: ec5eef7712c6300086b3513d317338d846900c6a.
=> Release 0.4.5

codecov_cli/commands/empty_upload.py, codecov_cli/services/empty_upload/__init__.py, tests/services/empty_upload/test_empty_upload.py
Fixes: https://github.com/codecov/engineering-team/issues/1016
API change: https://github.com/codecov/codecov-api/pull/362
=> feat: add force flag to empty upload

setup.py
Release PR for 0.4.6
I've updated the version name and committed: 6f256a3273bd59ced0347f26a2366bacb0775bf2.
=> Release 0.4.6

setup.py
Release PR for 0.4.7
I've updated the version name and committed: 862126fd098a0b192c702bd505aae6a241bbc93c.
=> Release 0.4.7

setup.py
Release PR for 0.4.8
I've updated the version name and committed: 26fea57d7107cd01756f13ebda016657f7164eb2.
=> Release 0.4.8

codecov_cli/helpers/request.py, tests/helpers/test_upload_sender.py
fixes: https://github.com/codecov/codecov-cli/issues/351
=> feat: retry requests on 502 responses

codecov_cli/services/upload/file_finder.py, tests/services/upload/test_coverage_file_finder.py
fixes: https://github.com/codecov/engineering-team/issues/1143
=> feat: include user specified files even if excluded

setup.py
Release PR for 0.4.9
I've updated the version name and committed: afcfe58c3ea84df7669a203267d1a0bab0b35410.
=> Release 0.4.9

setup.py
Release PR for 0.5.1
I've updated the version name and committed: cddb4d2dbb686324cadb130a57642733b74dfb0c.
=> Release 0.5.1

setup.py
Release PR for 0.5.2
I've updated the version name and committed: e36f3bbb56f296186530eabf40a05c0771a831d2.
=> Release 0.5.2

setup.py
Release PR for 0.6.0
I've updated the version name and committed: 8c869787ab875e0f2a8468a7ad16124d0b6de5db.
=> Release 0.6.0

codecov_cli/helpers/request.py, tests/helpers/test_upload_sender.py
Fixes: https://github.com/codecov/engineering-team/issues/1709
=> fix: retry all 5xx status code errors

setup.py
Release PR for 0.7.2
I've updated the version name and committed: 10a8dc66c62da7d5a4aa26a9b901716e2465216b.
=> Release 0.7.2

setup.py
Release PR for 0.7.3
I've updated the version name and committed: f8931a5be4caa57e8cfe732224b4b7048609c872.
=> Release 0.7.3

codecov_cli/helpers/folder_searcher.py, codecov_cli/services/upload/file_finder.py, tests/commands/test_process_test_results.py
Closes: https://github.com/codecov/codecov-cli/issues/449
=> feat: disable search means don't search for explicitly mentioned files

codecov_cli/helpers/folder_searcher.py, codecov_cli/services/upload/file_finder.py, tests/commands/test_process_test_results.py
Reverts codecov/codecov-cli#479
=> Revert "feat: disable search means don't search for explicitly mentioned files"

setup.py
Release PR for 0.7.4
I've updated the version name and committed: 87e04fafa74cc1e47b438a1fc9b2e31600695c2b.
=> Release 0.7.4

codecov_cli/helpers/request.py, tests/helpers/test_request.py
fixes https://github.com/codecov/codecov-cli/issues/469
fixes https://github.com/codecov/codecov-cli/issues/468
fixes https://github.com/codecov/codecov-action/issues/1498
=> fix: sanitize yaml token from logs

setup.py
Release PR for 0.7.6
I've updated the version name and committed: 04961d178e34181214c1b4624c9a180ed7634813.
=> Release 0.7.6

setup.py
Release PR for v0.9.0
I've updated the version name and committed: 93c7d03ff9d0679e69a659724dca003cf56142c2.
=> Release v0.9.0

setup.py
Release PR for 9.0.1
I've updated the version name and committed: cb2308119ad94bb7cdb5f7519d1172d81a013be9.
=> Release 9.0.1

setup.py
Release PR for 9.0.2
I've updated the version name and committed: c4f00a5bf5af7cf07bcb2593435a88eb7b865b96.
=> Release 9.0.2

setup.py
Release PR for 9.0.3
I've updated the version name and committed: d1237dea418b884b6d3c7e356d7ee12f3124cc14.
=> Release 9.0.3

setup.py
Release PR for 9.0.4
I've updated the version name and committed: 0c83ae4c53d6aa5af16f0d792e7f682265c70794.
=> Release 9.0.4

setup.py
Release PR for 0.9.4
I've updated the version name and committed: 9784dea8ad92c54369065b81fc1a301c938af94c.
=> Release 0.9.4

setup.py
Release PR for 9.1.0
I've updated the version name and committed: 3c746ee4c03799c74e5dd5addab25de03cceaeee.
=> Release 9.1.0

setup.py
Release PR for 9.1.1
I've updated the version name and committed: 9d29dab8f68832e8e266e08c01d3e1fe8cccf4db.
=> Release 9.1.1

codecov_cli/services/upload/file_finder.py
fixes https://github.com/codecov/codecov-cli/issues/482
=> fix: convert exclude folders to strs

setup.py
Release PR for 10.0.1
I've updated the version name and committed: ff31a35285659f5e270cce03fbf375c37635f819.
=> Release 10.0.1

pyproject.toml
Release PR for 10.1.0
I've updated the version name and committed: 20ba9d1fa5d120cb81caabc8e7de0becea90300c.
=> Release 10.1.0

pyproject.toml
Release PR for 10.1.1
I've updated the version name and committed: 617956d7b11337a9e9dfbc88857b1798233bed35.
=> Release 10.1.1

pyproject.toml
Release PR for 10.2.0
I've updated the version name and committed: 389bfd4b7295c3dc6d2948f4ea12e616561cbafd.
=> Release 10.2.0

pyproject.toml
Reverts codecov/codecov-cli#655
=> Revert "Release 10.2.1"
